name: GeyserPlaceholders
version: ${project.version}
main: com.github.imdabigboss.geyserplaceholders.GeyserPlaceholders
api-version: 1.19
softdepend: [Geyser-Spigot, PlaceholderAPI]
authors: [ImDaBigBossm, _FabioTNT]