name: GeyserPlaceholders
version: ${project.version}
main: com.github.imdabigboss.geyserplaceholders.GeyserPlaceholders
api-version: 1.15
softdepend: [Geyser-Spigot, PlaceholderAPI]
authors: [ImDaBigBoss]